server:
  port: 8084
spring:
  config:
    import: optional:file:.env[.properties]
  elasticsearch:
    uris: http://localhost:9200
  rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 5672




  kafka:
    consumer:
      group-id: 1
    bootstrap-servers: localhost:9092
    topic:
      name: OrderToNotifications
  main:
    allow-bean-definition-overriding: true




cache:
  redis:
    host: localhost
    port: 6379



web:
  integration:
    paymentsUrl: http://localhost:8083/api/payment
    warehouseUrl: http://localhost:8081/api/warehouse
    pricesUrl: http://localhost:8082/api/prices
resilience4j.ratelimiter:
  instances:
    backendA:
      limitForPeriod: 10
      limitRefreshPeriod: 1s
      timeoutDuration: 0
      registerHealthIndicator: true
      eventConsumerBufferSize: 100
    backendB:
      limitForPeriod: 6
      limitRefreshPeriod: 500ms
      timeoutDuration: 3s
rabbit:
  queue:
    name: message_queue
  delay_queue:
    name: delay_queue


