server:
  port: 8081
spring:
  liquibase:
    enabled: false
  application:
    name: warehouse-server
  main:
    allow-circular-references: true
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: danilanovikov
    password: demo2228
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
  config:
    import: optional:file:.env[.properties]
  kafka:
    consumer:
      group-id: 1
    bootstrap-servers: localhost:9092
    topic:
      name: OrderToWarehouse
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka
app:
  redis:
    host: localhost
    port: 6379
  cache:
    cacheType: redis
    caches:
      orderAfterCreate:
        expiry: 5m
      orderById:
        expiry: 10m
      orders:
        expiry: 10m
      comment:
        expiry: 14d
      ordersWithPagination:
        expiry: 20m

integration:
  geolocation:
      api_key: f5c5a2a3eb0f4c39ace02a29628fd8df
